package schema

// Generated by https://quicktype.io

type UserResponse struct {
	User User `json:"user"`
}

type User struct {
	Uid            string   `json:"uid"`            
	CreatedAt      string   `json:"created_at"`     
	UpdatedAt      string   `json:"updated_at"`     
	Email          string   `json:"email"`          
	Username       string   `json:"username"`       
	FirstName      string   `json:"first_name"`     
	LastName       string   `json:"last_name"`      
	Company        string   `json:"company"`        
	OrgUid         []string `json:"org_uid"`        
	SharedOrgUid   []string `json:"shared_org_uid"` 
	MobileNumber   string   `json:"mobile_number"`  
	CountryCode    string   `json:"country_code"`   
	TfaStatus      string   `json:"tfa_status"`     
	AuthyID        string   `json:"authy_id"`       
	Active         bool     `json:"active"`         
	FailedAttempts int64    `json:"failed_attempts"`
	Authtoken      string   `json:"authtoken"`      
	Roles          []Role   `json:"roles"`          
}

type Role struct {
	Uid         string   `json:"uid"`        
	Name        string   `json:"name"`       
	Description string   `json:"description"`
	Users       []string `json:"users"`      
	CreatedAt   string   `json:"created_at"` 
	UpdatedAt   string   `json:"updated_at"` 
	APIKey      string   `json:"api_key"`    
	Rules       []Rule   `json:"rules"`      
}

type Rule struct {
	Module       string   `json:"module"`      
	Locales      []string `json:"locales"`     
	ACL          ACL      `json:"acl"`         
	Environments []string `json:"environments"`
	Assets       []string `json:"assets"`      
}

