/*
Contentstack Content Delivery API OpenAPI Specification

Testing GlobalFieldsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package management

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/davidalpert/go-contentstack/v1/management"
)

func Test_management_GlobalFieldsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GlobalFieldsApiService Getallglobalfields", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.GlobalFieldsApi.Getallglobalfields(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GlobalFieldsApiService Getasingleglobalfield", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var globalFieldUid string

		httpRes, err := apiClient.GlobalFieldsApi.Getasingleglobalfield(context.Background(), globalFieldUid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
