/*
Contentstack Content Delivery API OpenAPI Specification

Testing ContentTypesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package management

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/davidalpert/go-contentstack/v1/management"
)

func Test_management_ContentTypesApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContentTypesApiService Getallcontenttypes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ContentTypesApi.Getallcontenttypes(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContentTypesApiService Getasinglecontenttype", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contentTypeUid string

		httpRes, err := apiClient.ContentTypesApi.Getasinglecontenttype(context.Background(), contentTypeUid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
