/*
Contentstack Content Delivery API OpenAPI Specification

Testing QueriesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package management

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/davidalpert/go-contentstack/v1/management"
)

func Test_management_QueriesApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test QueriesApiService GetallentriesEqualsoperatorEqualsoperatorwithingroupEqualsoperatorwithinmodularblocksNotEqualsoperator", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var contentTypeUid string

		httpRes, err := apiClient.QueriesApi.GetallentriesEqualsoperatorEqualsoperatorwithingroupEqualsoperatorwithinmodularblocksNotEqualsoperator(context.Background(), contentTypeUid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
