/*
Contentstack Content Delivery API OpenAPI Specification

Testing AssetsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package management

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/davidalpert/go-contentstack/v1/management"
)

func Test_management_AssetsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AssetsApiService Getallassets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.AssetsApi.Getallassets(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AssetsApiService Getasingleasset", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var assetUid string

		httpRes, err := apiClient.AssetsApi.Getasingleasset(context.Background(), assetUid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
